version: '3'
services:
  web:
    build: ./web
    ports:
      - "8663:8663"
    links:
      - api
    volumes:
      - ./web/src:/app/src
  api:
    build: ./api
    ports:
      - "8662:8662"
    links:
      - aqueduct-remote
    volumes:
      - ./api/data:/app/data
      - ./api/dist:/app/dist
  aqueduct-remote:
    build: ./aqueduct-remote
    ports:
      - "8700:8700"
    environment:
      - PARITY_NODE_URL
      - AQUEDUCT_API_KEY_ID
      - ETHEREUM_CHAIN
    links:
      - parity
    volumes:
      - ./aqueduct-remote/dist:/app/dist
  parity:
    image: parity/parity:v1.10.1
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
      - "8180:8180"
    environment:
      - ETHEREUM_CHAIN
    volumes:
      - ./parity-data:/root/.local/share/io.parity.ethereum/
    command: "--force-ui --unsafe-expose --chain $ETHEREUM_CHAIN --base-path /root/.local/share/io.parity.ethereum/"


